version: '3'

tasks:
  build:
    cmds:
      - go build -o app.exe cmd/server/main.go
    
  test:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - golangci-lint run

  run:
    cmds:
      - docker-compose up --build

  integration-test:
    cmds:
      - docker-compose up -d db
      - go test -tags=integration -v ./...
    env:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DB: postgres
      DB_HOST: localhost
      DB_TABLE: postgres
      DB_PORT: 5432
      SSL_MODE: disable

  acceptance-tests:
    cmds:
      - docker-compose up -d --build
      - go test -tags=e2e -v ./...